In [106]:
import pandas as pd
import json
import sqlite3
pd.set_option('display.float_format', lambda x: f'{x:,.2f}')

# Data prep

In [77]:
agents_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/agents_cleaned.json")
agents_df.rename(columns={
    "Agent_ID":"agentid",
    "Name":"name",
    "Phone":"phone",
    "Email":"email",
    "commission_rate":"commissionrate",
    "deals_closed":"dealsclosed",
    "rating":"rating",
    "experience_years":"experienceyears",
    "avg_closing_days":"avgclosingdays"
}, inplace=True)
agents_df.head()

,agentid,name,phone,email,commissionrate,dealsclosed,rating,experienceyears,avgclosingdays
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [11]:
buyers_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/buyers_cleaned.json")
buyers_df.rename(columns={
    "buyer_id":"buyerid",
    "sale_id":"saleid",
    "buyer_type":"buyertype",
    "payment_mode":"paymentmode",
    "loan_taken":"loantaken",
    "loan_provider":"loanprovider",
    "loan_amount":"loanamount"
}, inplace=True)
buyers_df.head()

,buyerid,saleid,buyertype,paymentmode,loantaken,loanprovider,loanamount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [3]:
listings_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/listings_final_expanded.json")
listings_df.rename(columns={
    "Listing_ID":"listingid",
    "City":"city",
    "Property_Type":"propertytype",
    "Price":"price",
    "Sqft":"sqft",
    "Date_Listed":"datelisted",
    "Agent_ID":"agentid",
    "Latitude":"latitude",
    "Longitude":"longitude"
}, inplace=True)
listings_df.head()

,listingid,city,propertytype,price,sqft,datelisted,agentid,latitude,longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [12]:
sales_df = pd.read_csv("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/sales_cleaned.csv")
sales_df.rename(columns={
    "Listing_ID":"listingid",
    "Sale_Price":"saleprice",
    "Date_Sold":"datesold",
    "Days_on_Market":"daysonmarket"
}, inplace=True)
sales_df.head()

  listingid     saleprice    datesold  daysonmarket
0    L01179  9.255800e+05  2023-07-07     65.005560
1    L00866  1.054160e+05  2023-06-14     38.004620
2    L00102  1.825184e+06  2023-09-09     22.992622
3    L00440  1.932085e+06  2023-10-29     72.012274
4    L00059  7.765860e+05  2023-05-01    116.000152

In [13]:
property_df = pd.read_json("/Users/mukundanramesh/projects/guvi-python-sql-pandas-project-1/datasets/property_attributes_final_expanded.json")
property_df.rename(columns={
    "attribute_id":"attributeid",
    "listing_id":"listingid",
    "floor_number":"floornumber",
    "total_floors":"totalfloors",
    "year_built":"yearbuilt",
    "is_rented":"isrented",
    "tenant_count":"tenantcount",
    "furnishing_status":"furnishingstatus",
    "metro_distance_km":"metrodistancekm",
    "parking_available":"parkingavailable",
    "power_backup":"powerbackup"
}, inplace=True)
property_df.head()

,attributeid,listingid,bedrooms,bathrooms,floornumber,totalfloors,yearbuilt,isrented,tenantcount,furnishingstatus,metrodistancekm,parkingavailable,powerbackup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [14]:
display(agents_df.info())
display(buyers_df.info())
display(listings_df.info())
display(property_df.info())
display(sales_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   agentid          50 non-null     object
 1   name             50 non-null     object
 2   phone            50 non-null     object
 3   email            50 non-null     object
 4   commissionrate   50 non-null     float64
 5   dealsclosed      50 non-null     int64
 6   rating           50 non-null     float64
 7   experienceyears  50 non-null     int64
 8   avgclosingdays   50 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.6+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   buyerid       20000 non-null  int64
 1   saleid        20000 non-null  object
 2   buyertype     20000 non-null  object
 3   paymentmode   20000 non-null  object
 4   loantaken     20000 non-null  bool
 5   loanprovider  10034 non-null  object
 6   loanamount    20000 non-null  int64
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   listingid     21200 non-null  object
 1   city          21200 non-null  object
 2   propertytype  21200 non-null  object
 3   price         21200 non-null  float64
 4   sqft          21200 non-null  float64
 5   datelisted    21200 non-null  object
 6   agentid       21200 non-null  object
 7   latitude      21200 non-null  float64
 8   longitude     21200 non-null  float64
dtypes: float64(4), object(5)
memory usage: 1.5+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   attributeid       21200 non-null  int64
 1   listingid         21200 non-null  object
 2   bedrooms          21200 non-null  int64
 3   bathrooms         21200 non-null  int64
 4   floornumber       21200 non-null  int64
 5   totalfloors       21200 non-null  int64
 6   yearbuilt         21200 non-null  int64
 7   isrented          21200 non-null  bool
 8   tenantcount       21200 non-null  int64
 9   furnishingstatus  21200 non-null  object
 10  metrodistancekm   21200 non-null  float64
 11  parkingavailable  21200 non-null  bool
 12  powerbackup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   listingid     720 non-null    object
 1   saleprice     720 non-null    float64
 2   datesold      720 non-null    object
 3   daysonmarket  720 non-null    float64
dtypes: float64(2), object(2)
memory usage: 22.6+ KB

None

# Database design

In [15]:
conn = sqlite3.connect("project.db")
cursor = conn.cursor()
conn.execute("PRAGMA foreign_keys = ON;")

In [26]:
#Query to create the agents table
agents_table_query = """
CREATE TABLE agents(
    agentid TEXT PRIMARY KEY,
    name TEXT,
    phone TEXT,
    email TEXT,
    commissionrate REAL,
    dealsclosed INTEGER,
    rating REAL,
    experienceyears INTEGER,
    avgclosingdays INTEGER
);
"""
cursor.execute(agents_table_query)
agents_df.to_sql("agents", conn, if_exists="append", index=False)
conn.commit()

In [21]:
agents_select_query = "select * from agents limit 1;"
result = pd.read_sql(agents_select_query, conn)
print(result)

  agentid         name            phone                 email  commissionrate  \
0   A0001  Agent A0001  +1-534-665-8373  a0001@realestate.com             2.0

   dealsclosed  rating  experienceyears  avgclosingdays
0           52     4.3               10              64

In [27]:
#Query to create the lisiting table
listings_table_query = """
CREATE TABLE listings(
    listingid TEXT PRIMARY KEY,
    city TEXT,
    propertytype TEXT,
    price REAL,
    sqft REAL,
    datelisted DATE,
    agentid TEXT,
    latitude REAL,
    longitude REAL,

    FOREIGN KEY(agentid)
        REFERENCES agents(agentid)
);
"""
cursor.execute(listings_table_query)
listings_df.to_sql("listings", conn, if_exists="append", index=False)
conn.commit()

In [31]:
listings_select_query = "select * from listings limit 1;"
result = pd.read_sql(listings_select_query, conn)
print(result)

  listingid      city propertytype         price         sqft  datelisted  \
0    L00001  New York    Apartment  1.655144e+06  2753.009121  2023-05-06

  agentid   latitude  longitude
0   A0015  33.965208 -69.861589

In [28]:
#Query to create the sales table
sales_table_query = """
CREATE TABLE sales(
    listingid TEXT PRIMARY KEY,
    saleprice REAL,
    datesold DATE,
    daysonmarket INTEGER,

    FOREIGN KEY(listingid)
        REFERENCES listings(listingid)
);
"""
cursor.execute(sales_table_query)
sales_df.to_sql("sales", conn, if_exists="append", index=False)
conn.commit()

In [ ]:
sales_select_query = "select * from sales limit 1;"
result = pd.read_sql(sales_select_query, conn)
print(result)

  listingid      saleprice    datesold  daysonmarket
0    L01179  925580.004193  2023-07-07      65.00556

In [29]:
#Query to create the buyers table
buyers_table_query = """
CREATE TABLE buyers(
    buyerid INTEGER PRIMARY KEY,
    saleid TEXT,

    buyertype TEXT,
    paymentmode TEXT,
    loantaken BOOLEAN,
    loanprovider TEXT,
    loanamount REAL,

    FOREIGN KEY(saleid)
        REFERENCES sales(listingid)
);
"""
cursor.execute(buyers_table_query)
buyers_df.to_sql("buyers", conn, if_exists="append", index=False)
conn.commit()

In [ ]:
buyers_select_query = "select * from buyers limit 1;"
result = pd.read_sql(buyers_select_query, conn)
print(result)

   buyerid  saleid buyertype paymentmode  loantaken loanprovider  loanamount
0        1  L01179  End User        Cash          0         None         0.0

In [30]:
property_attributes_table_query = """
CREATE TABLE property_attributes(
    attributeid INTEGER PRIMARY KEY,
    listingid TEXT,
    bedrooms INTEGER,
    bathrooms INTEGER,
    floornumber INTEGER,
    totalfloors INTEGER,
    yearbuilt INTEGER,
    isrented BOOLEAN,
    tenantcount INTEGER,
    furnishingstatus TEXT,
    metrodistancekm REAL,
    parkingavailable BOOLEAN,
    powerbackup BOOLEAN,

    FOREIGN KEY(listingid)
        REFERENCES listings(listingid)
);
"""
cursor.execute(property_attributes_table_query)
property_df.to_sql("property_attributes", conn, if_exists="append", index=False)
conn.commit()

In [ ]:
property_select_query = "select * from property_attributes limit 1;"
result = pd.read_sql(property_select_query, conn)
print(result)

   attributeid listingid  bedrooms  bathrooms  floornumber  totalfloors  \
0            1    L00001         5          3            9            9

   yearbuilt  isrented  tenantcount furnishingstatus  metrodistancekm  \
0       2001         1            4        Furnished             7.26

   parkingavailable  powerbackup
0                 0            1

In [32]:
# Agents
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_agents_rating
ON agents(rating);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_agents_experience
ON agents(experienceyears);
""")

# Listings
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_city
ON listings(city);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_propertytype
ON listings(propertytype);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_price
ON listings(price);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_listings_agentid
ON listings(agentid);
""")

# Sales
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_sales_datesold
ON sales(datesold);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_sales_saleprice
ON sales(saleprice);
""")

# Buyers
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_buyers_saleid
ON buyers(saleid);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_buyers_buyertype
ON buyers(buyertype);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_buyers_paymentmode
ON buyers(paymentmode);
""")

# Property Attributes
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_bedrooms
ON property_attributes(bedrooms);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_yearbuilt
ON property_attributes(yearbuilt);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_metrodistance
ON property_attributes(metrodistancekm);
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_property_listingid
ON property_attributes(listingid);
""")

conn.commit()

print("All indexes created successfully.")

All indexes created successfully.

# SQL analysis

## Property & Pricing Analysis

### 1. What is the average listing price by city?

In [48]:
query1 = """
SELECT city,ROUND(AVG(price), 2) AS average_listing_price
FROM listings
GROUP BY city
ORDER BY average_listing_price DESC;
"""
result1 = pd.read_sql(query1, conn)
result1

          city  average_listing_price
0     New York             2493319.74
1      Phoenix             2459961.76
2  Los Angeles             2442418.31
3      Houston             2436811.00
4      Chicago             2430677.90

### 2. What is the average price per square foot by property type?

In [49]:
query2 = """
SELECT propertytype,ROUND(AVG(price / sqft), 2) AS avg_price_per_sqft FROM listings
GROUP BY propertytype
ORDER BY avg_price_per_sqft DESC;
"""
result2 = pd.read_sql(query2, conn)
result2

  propertytype  avg_price_per_sqft
0        House              796.04
1    Apartment              792.20
2    Townhouse              789.75
3        Condo              754.68

### 3. How does furnishing status impact property prices?

In [52]:
query3 = """
SELECT p.furnishingstatus,ROUND(AVG(l.price), 2) AS average_price FROM listings l
JOIN property_attributes p ON l.listingid = p.listingid
GROUP BY p.furnishingstatus
ORDER BY average_price DESC;"""
result3 = pd.read_sql(query3, conn)
display(result3)
interpretation = """
Interpretation
* Furnished properties have the highest average price.
* Semi-Furnished properties are almost identical in price (difference of only about 2,346).
* Unfurnished properties have the lowest average price.

Observation
The difference is very small:
Furnished vs Semi-Furnished -> ~2.3K
Furnished vs Unfurnished -> ~29.6K
"""
print(interpretation)

  furnishingstatus  average_price
0        Furnished     2463539.06
1   Semi-Furnished     2461192.65
2      Unfurnished     2433975.10

Interpretation
* Furnished properties have the highest average price.
* Semi-Furnished properties are almost identical in price (difference of only about 2,346).
* Unfurnished properties have the lowest average price.

Observation
The difference is very small:
Furnished vs Semi-Furnished -> ~2.3K
Furnished vs Unfurnished -> ~29.6K

### 4. Do properties closer to metro stations command higher prices?

In [55]:
query4 = """
SELECT
    CASE
        WHEN p.metrodistancekm <= 1 THEN 'Within 1 km'
        WHEN p.metrodistancekm <= 3 THEN '1 - 3 km'
        WHEN p.metrodistancekm <= 5 THEN '3 - 5 km'
        ELSE 'More than 5 km'
    END AS metro_distance,
    COUNT(*) AS total_properties,
    ROUND(AVG(l.price), 2) AS average_price
FROM listings l
JOIN property_attributes p
ON l.listingid = p.listingid
GROUP BY metro_distance
ORDER BY average_price DESC;"""
result4 = pd.read_sql(query4, conn)
display(result4)
interpretation = """
Interpretation:
* Properties more than 5 km from a metro station have the highest average price.
* Properties within 1 km have the lowest average price.
The difference between the 1–3 km and 3–5 km groups is quite small.

Conclusion
No. This dataset does not indicate that properties closer to metro stations command higher prices. 
In fact, properties located more than 5 km away have the highest average listing price."""
print(interpretation)

   metro_distance  total_properties  average_price
0  More than 5 km             13876     2483642.71
1        1 - 3 km              2969     2399214.25
2        3 - 5 km              2954     2392399.27
3     Within 1 km              1401     2386849.26

Interpretation:
* Properties more than 5 km from a metro station have the highest average price.
* Properties within 1 km have the lowest average price.
The difference between the 1–3 km and 3–5 km groups is quite small.

Conclusion
No. This dataset does not indicate that properties closer to metro stations command higher prices.
In fact, properties located more than 5 km away have the highest average listing price.

### 5. Are rented properties priced differently from non-rented ones?

In [57]:
query5 = """
SELECT
    CASE
        WHEN p.isrented = 1 THEN 'Rented'
        ELSE 'Non Rented'
    END AS rental_status,
    COUNT(*) AS total_properties,
    ROUND(AVG(l.price), 2) AS average_price
FROM listings l
JOIN property_attributes p
ON l.listingid = p.listingid
GROUP BY rental_status
ORDER BY average_price DESC;
"""
result5 = pd.read_sql(query5, conn)
display(result5)
interpretation = """
Interpretation:
The average prices of rented and non-rented properties are almost identical. 
This suggests that rental status alone does not have a significant impact on property prices in this dataset.
"""
print(interpretation)

  rental_status  total_properties  average_price
0        Rented             10578      2457184.9
1    Non Rented             10622      2448250.3

Interpretation:
The average prices of rented and non-rented properties are almost identical.
This suggests that rental status alone does not have a significant impact on property prices in this dataset.

### 6. How do bedrooms and bathrooms affect pricing?

In [72]:
query6 = """
SELECT p.bedrooms,p.bathrooms,COUNT(*) AS total_properties,ROUND(AVG(l.price), 2) AS average_price
FROM listings l
JOIN property_attributes p
ON l.listingid = p.listingid
GROUP BY p.bedrooms,p.bathrooms
ORDER BY p.bedrooms,p.bathrooms;
"""
result6 = pd.read_sql(query6, conn)
display(result6) 
interpretation = """
The number of bedrooms and bathrooms alone does not appear to be a strong predictor of property price in this dataset. 
Property prices likely depend on a combination of factors such as city, property type, square footage, furnishing status, and location rather than just room counts."""
print(interpretation)

    bedrooms  bathrooms  total_properties  average_price
0          1          1              1040     2434001.41
1          1          2              1047     2509474.77
2          1          3              1028     2459032.59
3          1          4              1094     2455532.96
4          2          1              1068     2455735.36
5          2          2              1127     2378687.66
6          2          3              1060     2482618.93
7          2          4              1021     2555766.23
8          3          1              1032     2426007.97
9          3          2              1064     2409122.73
10         3          3              1030     2455024.25
11         3          4              1068     2478881.22
12         4          1              1080     2434956.38
13         4          2              1037     2450749.99
14         4          3              1034     2393515.03
15         4          4              1118     2471535.90
16         5          1              1095     2384940.47
17         5          2              1066     2478068.17
18         5          3              1066     2424066.83
19         5          4              1025     2527191.97

The number of bedrooms and bathrooms alone does not appear to be a strong predictor of property price in this dataset.
Property prices likely depend on a combination of factors such as city, property type, square footage, furnishing status, and location rather than just room counts.

### 7. Do properties with parking and power backup sell at higher prices?

In [61]:
query7 = """
SELECT
    CASE
        WHEN p.parkingavailable = 1 THEN 'Parking'
        ELSE 'No Parking'
    END AS parking,
    CASE
        WHEN p.powerbackup = 1 THEN 'Power Backup'
        ELSE 'No Power Backup'
    END AS power_backup,
    COUNT(*) AS total_properties,
    ROUND(AVG(l.price), 2) AS average_price
FROM listings l
JOIN property_attributes p
ON l.listingid = p.listingid
GROUP BY p.parkingavailable,p.powerbackup
ORDER BY average_price DESC;"""
result7 = pd.read_sql(query7, conn)
display(result7)
interpretation = """
Interpretation:
* Properties with both parking and power backup have the highest average price.
* Properties with no parking and no power backup have the lowest average price.
Conclusion:
Properties that offer both parking and power backup tend to have the highest average prices. 
Although the price differences are modest, these amenities appear to add value and are associated with slightly higher-priced properties."""
print(interpretation)

      parking     power_backup  total_properties  average_price
0     Parking     Power Backup              5243     2465651.62
1     Parking  No Power Backup              5383     2462363.80
2  No Parking     Power Backup              5166     2446292.59
3  No Parking  No Power Backup              5408     2436677.75

Interpretation:
* Properties with both parking and power backup have the highest average price.
* Properties with no parking and no power backup have the lowest average price.
Conclusion:
Properties that offer both parking and power backup tend to have the highest average prices.
Although the price differences are modest, these amenities appear to add value and are associated with slightly higher-priced properties.

### 8. How does year built influence listing price?

In [71]:
query8 = """
SELECT
    CASE
        WHEN p.yearbuilt between 1990 and 1995  THEN 'Between 1990 and 1995'
        WHEN p.yearbuilt between 1996 and 2000  THEN 'Between 1996 and 2000'
        WHEN p.yearbuilt between 2001 and 2005  THEN 'Between 2001 and 2005'
        WHEN p.yearbuilt between 2006 and 2010  THEN 'Between 2006 and 2010'
        WHEN p.yearbuilt between 2011 and 2015  THEN 'Between 2011 and 2015'
        WHEN p.yearbuilt between 2016 and 2020  THEN 'Between 2016 and 2020'
        WHEN p.yearbuilt between 2021 and 2025  THEN 'Between 2021 and 2025'
        ELSE 'Other'
    END AS built_between,
    COUNT(*) AS total_properties,
    ROUND(AVG(l.price), 2) AS average_price
FROM listings l
JOIN property_attributes p
ON l.listingid = p.listingid
GROUP BY built_between
ORDER BY average_price DESC
"""
result8 = pd.read_sql(query8, conn)
display(result8)
interpretation = """
Observations
* The oldest properties (1990–1995) have the highest average listing price.
* The newest properties (2021–2025) rank second.
* Properties built between 2011 and 2015 have the lowest average price.
There is no consistent relationship between the year a property was built and its listing price. 
While the newest properties are among the most expensive, the oldest properties (1990–1995) have the highest average prices. 
This suggests that year built alone is not a strong predictor of listing price in this dataset."""
print(interpretation)

           built_between  total_properties  average_price
0  Between 1990 and 1995              3550     2551996.76
1  Between 2021 and 2025              1952     2479104.02
2  Between 2016 and 2020              3237     2448048.06
3  Between 1996 and 2000              3158     2443509.48
4  Between 2001 and 2005              3070     2439561.83
5  Between 2006 and 2010              3055     2423376.40
6  Between 2011 and 2015              3178     2380369.04

Observations
* The oldest properties (1990–1995) have the highest average listing price.
* The newest properties (2021–2025) rank second.
* Properties built between 2011 and 2015 have the lowest average price.
There is no consistent relationship between the year a property was built and its listing price.
While the newest properties are among the most expensive, the oldest properties (1990–1995) have the highest average prices.
This suggests that year built alone is not a strong predictor of listing price in this dataset.

### 9. Which cities have the highest average property prices?

In [73]:
query9 = """
SELECT city,count(*) as total_listings,ROUND(AVG(price), 2) AS average_price FROM listings
GROUP BY city
ORDER BY average_price DESC;
"""
result9 = pd.read_sql(query9, conn)
display(result9)
interpretation = """
New York has the highest average listing price among the five cities, with an average property price of approximately 2.49 million. 
Phoenix follows closely, while Chicago has the lowest average listing price in the dataset."""
print(interpretation)

          city  total_listings  average_price
0     New York            4269     2493319.74
1      Phoenix            4229     2459961.76
2  Los Angeles            4318     2442418.31
3      Houston            4091     2436811.00
4      Chicago            4293     2430677.90

New York has the highest average listing price among the five cities, with an average property price of approximately 2.49 million.
Phoenix follows closely, while Chicago has the lowest average listing price in the dataset.

### 10.How are properties distributed across price buckets?

In [74]:
query10 = """
SELECT
    CASE
        WHEN price < 1000000 THEN 'Below 1M'
        WHEN price < 2000000 THEN '1M - 2M'
        WHEN price < 3000000 THEN '2M - 3M'
        WHEN price < 4000000 THEN '3M - 4M'
        ELSE 'Above 4M'
    END AS price_bucket,
    COUNT(*) AS total_properties
FROM listings
GROUP BY price_bucket
order by min(price);
"""
result10 = pd.read_sql(query10, conn)
display(result10)
interpretation = """
The largest proportion of properties falls in the 1M–2M price range, with 4,800 properties."""
print(interpretation)

  price_bucket  total_properties
0     Below 1M              4269
1      1M - 2M              4800
2      2M - 3M              4025
3      3M - 4M              4083
4     Above 4M              4023

The largest proportion of properties falls in the 1M–2M price range, with 4,800 properties.

## Sales & Market Performance

### 11.What is the average days on market by city?

In [82]:
query11 = """
SELECT l.city, ROUND(AVG(s.daysonmarket),0) as average_days_on_market
FROM listings l
join sales s on s.listingid = l.listingid
GROUP BY l.city
order by average_days_on_market desc;"""
result11 = pd.read_sql(query11, conn)
display(result11)
interpretation = """
Los Angeles has the highest average days on market (65 days), indicating that properties take the longest to sell among the five cities.
In contrast, Houston has the lowest average (59 days), suggesting a relatively faster-moving real estate market."""
print(interpretation)

          city  average_days_on_market
0  Los Angeles                    65.0
1      Chicago                    64.0
2     New York                    61.0
3      Phoenix                    60.0
4      Houston                    59.0

Los Angeles has the highest average days on market (65 days), indicating that properties take the longest to sell among the five cities.
In contrast, Houston has the lowest average (59 days), suggesting a relatively faster-moving real estate market.

### 12.Which property types sell the fastest?

In [84]:
query12 = """
SELECT l.propertytype, ROUND(avg(s.daysonmarket),0) as average_days_on_market
FROM listings l
join sales s on s.listingid = l.listingid
GROUP BY l.propertytype
order by average_days_on_market asc;"""
result12 = pd.read_sql(query12, conn)
display(result12)
interpretation = """
Houses have the shortest average time on the market (58 days), making them the fastest-selling property type in the dataset. 
Condos take the longest to sell (67 days), while apartments and townhouses have similar average selling times of approximately 61 days. 
This suggests that property type has a moderate influence on how quickly a property is sold."""
print(interpretation)

  propertytype  average_days_on_market
0        House                    58.0
1    Apartment                    61.0
2    Townhouse                    61.0
3        Condo                    67.0

Houses have the shortest average time on the market (58 days), making them the fastest-selling property type in the dataset.
Condos take the longest to sell (67 days), while apartments and townhouses have similar average selling times of approximately 61 days.
This suggests that property type has a moderate influence on how quickly a property is sold.

### 13.What percentage of properties are sold above listing price?

In [86]:
query13 = """
SELECT ROUND(SUM(
                CASE
                WHEN s.saleprice > l.price THEN 1
                ELSE 0
            END) * 100.0 / COUNT(*),
        2
    ) AS percentage_sold_above_listing
FROM listings l
JOIN sales s
ON l.listingid = s.listingid;"""
result13 = pd.read_sql(query13, conn)
display(result13)
interpretation = """
Approximately 49% of properties in the dataset were sold above their listing price, 
indicating that nearly half of the properties experienced competitive bidding or strong demand that drove the final sale price higher than the initial listing price."""
print(interpretation)

   percentage_sold_above_listing
0                          49.31

Approximately 49% of properties in the dataset were sold above their listing price,
indicating that nearly half of the properties experienced competitive bidding or strong demand that drove the final sale price higher than the initial listing price.

### 14.What is the sale-to-list price ratio by city?

In [88]:
query14 = """
SELECT l.city,round(avg(s.saleprice/l.price),4) as sale_to_list_ratio
FROM listings l
join sales s on s.listingid = l.listingid
GROUP BY l.city
order by sale_to_list_ratio desc;
"""
result14 = pd.read_sql(query14, conn)
display(result14)
interpretation = """
All five cities have sale-to-list ratios essentially equal to 1.0, meaning properties sell very close to their listing price everywhere. 
The differences between cities are too small to indicate any real variation in market heat"""    
print(interpretation)

          city  sale_to_list_ratio
0      Chicago              1.0015
1      Houston              1.0000
2  Los Angeles              0.9998
3     New York              0.9996
4      Phoenix              0.9989

All five cities have sale-to-list ratios essentially equal to 1.0, meaning properties sell very close to their listing price everywhere.
The differences between cities are too small to indicate any real variation in market heat

### 15.Which listings took more than 90 days to sell?

In [90]:
query15 = """
select listingid,daysonmarket from sales 
where daysonmarket >90
order by daysonmarket desc; 
"""
result15 = pd.read_sql(query15, conn)
display(result15)
interpretation = """
90 of 720 sold properties (26%) took more than 90 days to sell, with the longest reaching ~120 days
"""
print(interpretation)

    listingid  daysonmarket
0      L00157    120.018183
1      L00179    120.011468
2      L00259    120.010958
3      L00067    119.993220
4      L00287    119.970137
..        ...           ...
185    L00452     90.996134
186    L00045     90.992445
187    L00812     90.990111
188    L00568     90.006266
189    L00992     90.003498

[190 rows x 2 columns]

90 of 720 sold properties (26%) took more than 90 days to sell, with the longest reaching ~120 days

### 16.How does metro distance affect time on market?

In [93]:
query16 = """
select 
	   CASE
        WHEN p.metrodistancekm <= 1 THEN 'Within 1 km'
        WHEN p.metrodistancekm <= 3 THEN '1 - 3 km'
        WHEN p.metrodistancekm <= 5 THEN '3 - 5 km'
        ELSE 'More than 5 km'
    END AS metro_distance, AVG(s.daysonmarket) as average_days_on_market
from property_attributes p 
join sales s on s.listingid = p.listingid
group by metro_distance
order by average_days_on_market desc; 
"""
result16 = pd.read_sql(query16, conn)
display(result16)
interpretation = """
Time on market is essentially flat across all metro-distance bands (~60–65 days), with no consistent relationship between proximity to a metro and how quickly a property sells
"""
print(interpretation)

   metro_distance  average_days_on_market
0     Within 1 km               64.523678
1        1 - 3 km               64.276297
2  More than 5 km               60.673854
3        3 - 5 km               59.845491

Time on market is essentially flat across all metro-distance bands (~60–65 days), with no consistent relationship between proximity to a metro and how quickly a property sells

### 17.What is the monthly sales trend?

In [100]:
query17 = """
select strftime('%Y-%m', datesold) as month , count(*) as total_sales_per_month
from sales
group by month
order by month asc;
"""
result17 = pd.read_sql(query17, conn)
display(result17)
interpretation = """ 
The monthly sales trend shows a steady increase in property sales throughout 2023, reaching a peak in October 2023 with 64 sales. After October, sales began to decline gradually. 
Throughout 2024, the number of monthly sales continued to decrease, falling sharply towards the end of the period, with only 1 sale recorded in September 2024"""
print(interpretation)

      month  total_sales_per_month
0   2023-01                      7
1   2023-02                     17
2   2023-03                     20
3   2023-04                     36
4   2023-05                     45
5   2023-06                     31
6   2023-07                     48
7   2023-08                     50
8   2023-09                     46
9   2023-10                     64
10  2023-11                     46
11  2023-12                     42
12  2024-01                     44
13  2024-02                     44
14  2024-03                     39
15  2024-04                     29
16  2024-05                     45
17  2024-06                     29
18  2024-07                     24
19  2024-08                     13
20  2024-09                      1

The monthly sales trend shows a steady increase in property sales throughout 2023, reaching a peak in October 2023 with 64 sales. After October, sales began to decline gradually.
Throughout 2024, the number of monthly sales continued to decrease, falling sharply towards the end of the period, with only 1 sale recorded in September 2024

### 18.Which properties are currently unsold?

In [101]:
query18 = """
select * from listings l
where NOT EXISTS (select 1 from sales s where s.listingid = l.listingid);
"""
result18 = pd.read_sql(query18, conn)
display(result18)

,listingid,city,propertytype,price,sqft,datelisted,agentid,latitude,longitude
0,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
1,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878
2,L00009,New York,Townhouse,1.224551e+06,1522.007780,2024-05-13,A0025,32.302569,-94.556982
3,L00014,Chicago,Apartment,1.377440e+06,1900.998129,2023-10-01,A0047,29.772677,-95.162779
4,L00015,Los Angeles,House,1.069429e+06,3607.995839,2023-05-19,A0041,39.214998,-122.295145
...,...,...,...,...,...,...,...,...,...
20475,L21196,Phoenix,House,7.093553e+05,898.410000,2023-12-31,A0021,25.456929,-88.189857
20476,L21197,Phoenix,Condo,3.288420e+06,4195.680000,2023-07-23,A0005,40.926232,-80.167341
20477,L21198,Los Angeles,Apartment,1.667441e+06,8723.370000,2024-06-30,A0003,46.083306,-115.396164
20478,L21199,Los Angeles,Townhouse,1.648412e+06,8412.710000,2023-09-17,A0018,33.757737,-103.472564
20479,L21200,New York,Apartment,4.991528e+06,3994.920000,2023-07-28,A0008,42.222541,-119.219408

In [102]:
query18 = """
SELECT city, COUNT(*) AS total_unsold_properties
FROM listings l
WHERE NOT EXISTS (SELECT 1 FROM sales s WHERE s.listingid = l.listingid)
GROUP BY city
ORDER BY total_unsold_properties DESC;
"""
result18 = pd.read_sql(query18, conn)
display(result18)

          city  total_unsold_properties
0  Los Angeles                     4190
1      Chicago                     4137
2     New York                     4132
3      Phoenix                     4061
4      Houston                     3960

## Agent Performance

### 19.Which agents have closed the most sales?

In [103]:
query19 = """ 
select name,dealsclosed from agents order by dealsclosed desc;
""" 
result19 = pd.read_sql(query19, conn)
display(result19)

           name  dealsclosed
0   Agent A0003          297
1   Agent A0030          296
2   Agent A0010          292
3   Agent A0024          283
4   Agent A0011          270
5   Agent A0048          266
6   Agent A0035          262
7   Agent A0038          257
8   Agent A0044          236
9   Agent A0021          233
10  Agent A0042          231
11  Agent A0016          230
12  Agent A0031          226
13  Agent A0026          225
14  Agent A0009          218
15  Agent A0005          198
16  Agent A0025          188
17  Agent A0020          166
18  Agent A0027          157
19  Agent A0017          156
20  Agent A0040          153
21  Agent A0032          151
22  Agent A0039          142
23  Agent A0046          135
24  Agent A0007          127
25  Agent A0050          109
26  Agent A0045           99
27  Agent A0036           98
28  Agent A0047           91
29  Agent A0018           89
30  Agent A0043           85
31  Agent A0034           83
32  Agent A0041           77
33  Agent A0008           74
34  Agent A0028           69
35  Agent A0029           65
36  Agent A0006           63
37  Agent A0014           60
38  Agent A0022           56
39  Agent A0001           52
40  Agent A0015           50
41  Agent A0019           48
42  Agent A0004           31
43  Agent A0023           30
44  Agent A0002           26
45  Agent A0012           24
46  Agent A0049           17
47  Agent A0037           16
48  Agent A0033           14
49  Agent A0013           11

In [104]:
query_19_2 = """
select a.agentid,a.name,count(s.listingid) as closed_sales from listings l
join sales s on s.listingid = l.listingid
join agents a on a.agentid = l.agentid
group by a.agentid,a.name
order by closed_sales desc ;
"""
result_19_2 = pd.read_sql(query_19_2, conn)
display(result_19_2)

   agentid         name  closed_sales
0    A0042  Agent A0042            25
1    A0011  Agent A0011            24
2    A0014  Agent A0014            21
3    A0035  Agent A0035            21
4    A0043  Agent A0043            20
5    A0046  Agent A0046            20
6    A0007  Agent A0007            19
7    A0048  Agent A0048            19
8    A0027  Agent A0027            18
9    A0029  Agent A0029            18
10   A0009  Agent A0009            17
11   A0019  Agent A0019            17
12   A0021  Agent A0021            17
13   A0025  Agent A0025            17
14   A0050  Agent A0050            17
15   A0003  Agent A0003            16
16   A0015  Agent A0015            16
17   A0033  Agent A0033            16
18   A0036  Agent A0036            16
19   A0039  Agent A0039            16
20   A0001  Agent A0001            15
21   A0006  Agent A0006            15
22   A0010  Agent A0010            15
23   A0016  Agent A0016            15
24   A0041  Agent A0041            15
25   A0017  Agent A0017            14
26   A0024  Agent A0024            14
27   A0047  Agent A0047            14
28   A0018  Agent A0018            13
29   A0031  Agent A0031            13
30   A0040  Agent A0040            13
31   A0045  Agent A0045            13
32   A0023  Agent A0023            12
33   A0026  Agent A0026            12
34   A0037  Agent A0037            12
35   A0038  Agent A0038            12
36   A0004  Agent A0004            11
37   A0008  Agent A0008            11
38   A0012  Agent A0012            11
39   A0030  Agent A0030            11
40   A0005  Agent A0005            10
41   A0020  Agent A0020            10
42   A0028  Agent A0028            10
43   A0032  Agent A0032            10
44   A0049  Agent A0049            10
45   A0022  Agent A0022             9
46   A0002  Agent A0002             8
47   A0044  Agent A0044             8
48   A0013  Agent A0013             7
49   A0034  Agent A0034             7

### 20.Who are the top agents by total sales revenue?

In [110]:
query20 = """
select a.agentid,a.name,count(s.listingid) as no_of_listings_sold,sum(s.saleprice) as total_sales_revenue, round(avg(s.saleprice),2) as average_sales_revenue 
from listings l
join sales s on s.listingid = l.listingid
join agents a on a.agentid = l.agentid
group by a.agentid,a.name
order by total_sales_revenue desc ;
"""
result20 = pd.read_sql(query20, conn)
display(result20)
interpretation = """
Agent A0011 has the highest total sales revenue, amounting to approximately ~27 million and has sold 24 properties, with an average sales revenue of ~1.6 million per property.
followed by A0042 with ~27 million in total sales revenue and 25 properties sold, with an average sales revenue of ~1 million per property.
"""
print(interpretation)

,agentid,name,no_of_listings_sold,total_sales_revenue,average_sales_revenue
0,A0011,Agent A0011,24,"27,882,272.02","1,161,761.33"
1,A0042,Agent A0042,25,"27,191,605.99","1,087,664.24"
2,A0043,Agent A0043,20,"24,102,418.02","1,205,120.90"
3,A0035,Agent A0035,21,"22,725,751.99","1,082,178.67"
4,A0014,Agent A0014,21,"22,034,008.02","1,049,238.48"
5,A0046,Agent A0046,20,"21,335,804.97","1,066,790.25"
6,A0048,Agent A0048,19,"21,186,306.00","1,115,068.74"
7,A0027,Agent A0027,18,"21,099,696.96","1,172,205.39"
8,A0009,Agent A0009,17,"20,279,274.97","1,192,898.53"
9,A0029,Agent A0029,18,"19,586,498.02","1,088,138.78"
10,A0039,Agent A0039,16,"19,223,013.98","1,201,438.37"
11,A0036,Agent A0036,16,"19,209,543.94","1,200,596.50"
12,A0050,Agent A0050,17,"18,968,547.96","1,115,796.94"
13,A0025,Agent A0025,17,"18,818,591.05","1,106,975.94"
14,A0017,Agent A0017,14,"18,583,851.04","1,327,417.93"
15,A0007,Agent A0007,19,"18,414,480.00","969,183.16"
16,A0001,Agent A0001,15,"18,173,919.98","1,211,594.67"
17,A0015,Agent A0015,16,"17,752,856.04","1,109,553.50"
18,A0019,Agent A0019,17,"16,730,611.98","984,153.65"
19,A0021,Agent A0021,17,"16,548,308.01","973,429.88"
20,A0006,Agent A0006,15,"16,523,231.01","1,101,548.73"
21,A0031,Agent A0031,13,"15,723,293.00","1,209,484.08"
22,A0003,Agent A0003,16,"15,584,954.00","974,059.62"
23,A0018,Agent A0018,13,"15,539,876.00","1,195,375.08"
24,A0012,Agent A0012,11,"14,730,534.97","1,339,139.54"
25,A0023,Agent A0023,12,"14,634,873.95","1,219,572.83"
26,A0010,Agent A0010,15,"14,228,164.00","948,544.27"
27,A0033,Agent A0033,16,"14,202,148.96","887,634.31"
28,A0041,Agent A0041,15,"14,077,482.03","938,498.80"
29,A0049,Agent A0049,10,"13,954,945.00","1,395,494.50"
30,A0047,Agent A0047,14,"13,478,182.00","962,727.29"
31,A0016,Agent A0016,15,"13,450,352.05","896,690.14"
32,A0024,Agent A0024,14,"13,196,018.04","942,572.72"
33,A0004,Agent A0004,11,"12,754,766.05","1,159,524.19"
34,A0030,Agent A0030,11,"12,484,445.00","1,134,949.55"
35,A0037,Agent A0037,12,"12,314,990.00","1,026,249.17"
36,A0040,Agent A0040,13,"12,039,288.01","926,099.08"
37,A0045,Agent A0045,13,"11,819,072.04","909,159.39"
38,A0002,Agent A0002,8,"11,754,965.99","1,469,370.75"
39,A0008,Agent A0008,11,"11,071,897.04","1,006,536.09"
40,A0038,Agent A0038,12,"11,060,638.02","921,719.83"
41,A0032,Agent A0032,10,"10,653,319.95","1,065,331.99"
42,A0044,Agent A0044,8,"10,247,548.02","1,280,943.50"
43,A0005,Agent A0005,10,"10,114,386.01","1,011,438.60"
44,A0028,Agent A0028,10,"9,831,891.01","983,189.10"
45,A0020,Agent A0020,10,"9,605,503.02","960,550.30"
46,A0013,Agent A0013,7,"9,114,420.00","1,302,060.00"
47,A0026,Agent A0026,12,"8,479,517.99","706,626.50"
48,A0034,Agent A0034,7,"7,011,394.01","1,001,627.72"
49,A0022,Agent A0022,9,"6,303,600.99","700,400.11"

Agent A0011 has the highest total sales revenue, amounting to approximately ~27 million and has sold 24 properties, with an average sales revenue of ~1.6 million per property.
followed by A0042 with ~27 million in total sales revenue and 25 properties sold, with an average sales revenue of ~1 million per property.

### 21.Which agents close deals fastest?

In [115]:
query21 = """
select a.agentid,a.name,count(*) as total_deals_closed, round(avg(s.daysonmarket),0) as days_taken_to_close_deal
from listings l
join sales s on s.listingid = l.listingid
join agents a on a.agentid = l.agentid
group by a.agentid,a.name
order by days_taken_to_close_deal asc, total_deals_closed DESC;
"""
result21 = pd.read_sql(query21, conn)
display(result21)
interpretation = """
"""
print(interpretation)

   agentid         name  total_deals_closed  days_taken_to_close_deal
0    A0044  Agent A0044                   8                     37.00
1    A0013  Agent A0013                   7                     42.00
2    A0037  Agent A0037                  12                     45.00
3    A0002  Agent A0002                   8                     46.00
4    A0008  Agent A0008                  11                     47.00
5    A0017  Agent A0017                  14                     49.00
6    A0026  Agent A0026                  12                     50.00
7    A0010  Agent A0010                  15                     51.00
8    A0012  Agent A0012                  11                     51.00
9    A0043  Agent A0043                  20                     52.00
10   A0009  Agent A0009                  17                     53.00
11   A0018  Agent A0018                  13                     55.00
12   A0036  Agent A0036                  16                     56.00
13   A0041  Agent A0041                  15                     56.00
14   A0040  Agent A0040                  13                     56.00
15   A0028  Agent A0028                  10                     56.00
16   A0022  Agent A0022                   9                     56.00
17   A0023  Agent A0023                  12                     57.00
18   A0046  Agent A0046                  20                     60.00
19   A0027  Agent A0027                  18                     61.00
20   A0047  Agent A0047                  14                     61.00
21   A0029  Agent A0029                  18                     62.00
22   A0019  Agent A0019                  17                     62.00
23   A0001  Agent A0001                  15                     62.00
24   A0024  Agent A0024                  14                     62.00
25   A0030  Agent A0030                  11                     62.00
26   A0020  Agent A0020                  10                     62.00
27   A0049  Agent A0049                  10                     62.00
28   A0050  Agent A0050                  17                     63.00
29   A0033  Agent A0033                  16                     63.00
30   A0032  Agent A0032                  10                     63.00
31   A0007  Agent A0007                  19                     64.00
32   A0005  Agent A0005                  10                     64.00
33   A0011  Agent A0011                  24                     65.00
34   A0016  Agent A0016                  15                     65.00
35   A0015  Agent A0015                  16                     66.00
36   A0042  Agent A0042                  25                     67.00
37   A0014  Agent A0014                  21                     67.00
38   A0035  Agent A0035                  21                     67.00
39   A0039  Agent A0039                  16                     67.00
40   A0021  Agent A0021                  17                     68.00
41   A0034  Agent A0034                   7                     68.00
42   A0048  Agent A0048                  19                     69.00
43   A0031  Agent A0031                  13                     69.00
44   A0045  Agent A0045                  13                     69.00
45   A0038  Agent A0038                  12                     70.00
46   A0025  Agent A0025                  17                     71.00
47   A0003  Agent A0003                  16                     80.00
48   A0004  Agent A0004                  11                     80.00
49   A0006  Agent A0006                  15                     81.00

### 22.Does experience correlate with deals closed?

In [118]:
query22 = """
SELECT
  CASE
    WHEN experienceyears <= 5  THEN '0-5 yrs'
    WHEN experienceyears <= 10 THEN '6-10 yrs'
    WHEN experienceyears <= 15 THEN '11-15 yrs'
    WHEN experienceyears <= 20 THEN '16-20 yrs'
    ELSE '21+ yrs'
  END AS experience_band,
  COUNT(*) AS num_agents,
  ROUND(AVG(dealsclosed),0) AS avg_deals
FROM agents
GROUP BY experience_band
ORDER BY MIN(experienceyears);
"""
result22 = pd.read_sql(query22, conn)
display(result22)
agents = pd.read_sql("SELECT experienceyears, dealsclosed FROM agents", conn)
print("correlation:", round(agents['experienceyears'].corr(agents['dealsclosed']), 3))

  experience_band  num_agents  avg_deals
0         0-5 yrs           8     109.00
1        6-10 yrs           5     123.00
2       11-15 yrs          10     141.00
3       16-20 yrs          17     134.00
4         21+ yrs          10     166.00

correlation: 0.125

### 23.Do agents with higher ratings close deals faster?

In [119]:
query23 = """
select a.agentid,a.name,rating,round(avg(s.daysonmarket),0) as days_taken_to_close_deal
from listings l
join sales s on s.listingid = l.listingid
join agents a on a.agentid = l.agentid
group by a.agentid,a.name
order by rating asc, days_taken_to_close_deal asc;
 """
result23 = pd.read_sql(query23, conn)
display(result23)
print("correlation (rating vs avg days):", round(result23['rating'].corr(result23['days_taken_to_close_deal']), 3))

   agentid         name  rating  days_taken_to_close_deal
0    A0019  Agent A0019    3.10                     62.00
1    A0033  Agent A0033    3.10                     63.00
2    A0034  Agent A0034    3.10                     68.00
3    A0043  Agent A0043    3.20                     52.00
4    A0022  Agent A0022    3.20                     56.00
5    A0046  Agent A0046    3.20                     60.00
6    A0025  Agent A0025    3.20                     71.00
7    A0030  Agent A0030    3.30                     62.00
8    A0032  Agent A0032    3.30                     63.00
9    A0008  Agent A0008    3.40                     47.00
10   A0010  Agent A0010    3.40                     51.00
11   A0035  Agent A0035    3.40                     67.00
12   A0012  Agent A0012    3.50                     51.00
13   A0050  Agent A0050    3.50                     63.00
14   A0039  Agent A0039    3.50                     67.00
15   A0044  Agent A0044    3.60                     37.00
16   A0041  Agent A0041    3.60                     56.00
17   A0021  Agent A0021    3.60                     68.00
18   A0031  Agent A0031    3.60                     69.00
19   A0003  Agent A0003    3.60                     80.00
20   A0036  Agent A0036    3.70                     56.00
21   A0014  Agent A0014    3.70                     67.00
22   A0002  Agent A0002    3.80                     46.00
23   A0007  Agent A0007    3.80                     64.00
24   A0028  Agent A0028    4.00                     56.00
25   A0047  Agent A0047    4.00                     61.00
26   A0048  Agent A0048    4.00                     69.00
27   A0037  Agent A0037    4.10                     45.00
28   A0018  Agent A0018    4.10                     55.00
29   A0023  Agent A0023    4.10                     57.00
30   A0024  Agent A0024    4.10                     62.00
31   A0049  Agent A0049    4.10                     62.00
32   A0015  Agent A0015    4.10                     66.00
33   A0045  Agent A0045    4.20                     69.00
34   A0017  Agent A0017    4.30                     49.00
35   A0001  Agent A0001    4.30                     62.00
36   A0005  Agent A0005    4.30                     64.00
37   A0042  Agent A0042    4.30                     67.00
38   A0038  Agent A0038    4.30                     70.00
39   A0009  Agent A0009    4.40                     53.00
40   A0004  Agent A0004    4.50                     80.00
41   A0027  Agent A0027    4.60                     61.00
42   A0013  Agent A0013    4.80                     42.00
43   A0040  Agent A0040    4.80                     56.00
44   A0029  Agent A0029    4.80                     62.00
45   A0016  Agent A0016    4.80                     65.00
46   A0011  Agent A0011    4.90                     65.00
47   A0006  Agent A0006    4.90                     81.00
48   A0026  Agent A0026    5.00                     50.00
49   A0020  Agent A0020    5.00                     62.00

correlation (rating vs avg days): 0.033

### 24.What is the average commission earned by each agent?

In [120]:
query24 = """
select a.agentid,a.name,round(avg(s.saleprice *(a.commissionrate/100)),2) as avg_commission_per_sale
from listings l
join sales s on s.listingid = l.listingid
join agents a on a.agentid = l.agentid
group by a.agentid,a.name
order by avg_commission_per_sale desc;
"""
result24 = pd.read_sql(query24, conn)
display(result24)

   agentid         name  avg_commission_per_sale
0    A0009  Agent A0009                33,997.61
1    A0002  Agent A0002                32,326.16
2    A0035  Agent A0035                32,032.49
3    A0012  Agent A0012                31,737.61
4    A0030  Agent A0030                31,665.09
5    A0018  Agent A0018                31,438.36
6    A0031  Agent A0031                30,358.05
7    A0050  Agent A0050                28,564.40
8    A0017  Agent A0017                28,406.74
9    A0024  Agent A0024                27,805.90
10   A0003  Agent A0003                27,760.70
11   A0019  Agent A0019                27,556.30
12   A0032  Agent A0032                27,379.03
13   A0029  Agent A0029                26,659.40
14   A0021  Agent A0021                26,574.64
15   A0020  Agent A0020                25,646.69
16   A0034  Agent A0034                24,640.04
17   A0042  Agent A0042                24,363.68
18   A0001  Agent A0001                24,231.89
19   A0049  Agent A0049                23,723.41
20   A0011  Agent A0011                23,351.40
21   A0013  Agent A0013                23,176.67
22   A0023  Agent A0023                23,049.93
23   A0045  Agent A0045                22,728.98
24   A0033  Agent A0033                22,723.44
25   A0027  Agent A0027                22,506.34
26   A0025  Agent A0025                22,250.22
27   A0028  Agent A0028                22,121.75
28   A0043  Agent A0043                21,089.62
29   A0036  Agent A0036                20,770.32
30   A0014  Agent A0014                20,670.00
31   A0010  Agent A0010                20,298.85
32   A0004  Agent A0004                19,364.05
33   A0044  Agent A0044                18,573.68
34   A0037  Agent A0037                18,267.24
35   A0006  Agent A0006                17,404.47
36   A0008  Agent A0008                17,312.42
37   A0007  Agent A0007                17,251.46
38   A0046  Agent A0046                16,748.61
39   A0015  Agent A0015                16,532.35
40   A0039  Agent A0039                16,459.71
41   A0047  Agent A0047                15,692.45
42   A0048  Agent A0048                14,941.92
43   A0040  Agent A0040                14,632.37
44   A0022  Agent A0022                13,587.76
45   A0016  Agent A0016                13,002.01
46   A0041  Agent A0041                12,388.18
47   A0026  Agent A0026                11,518.01
48   A0038  Agent A0038                11,244.98
49   A0005  Agent A0005                11,226.97

### 25.Which agents currently have the most active listings?

In [125]:
query25 = """
select a.agentid,a.name,count(l.listingid) as active_listings from listings l
join agents a on a.agentid = l.agentid
where NOT EXISTS (select 1 from sales s where l.listingid = s.listingid)
group by a.agentid,a.name
ORDER BY active_listings DESC;
"""
result25 = pd.read_sql(query25, conn)
display(result25)
interpretation = """ 
Agents with the highest number of active listings are currently managing the largest property inventory. 
A higher number of active listings may indicate greater market responsibility or a larger client portfolio, although it could also suggest that some properties are taking longer to sell.
"""
print(interpretation)

   agentid         name  active_listings
0    A0023  Agent A0023              446
1    A0011  Agent A0011              439
2    A0008  Agent A0008              438
3    A0042  Agent A0042              435
4    A0014  Agent A0014              432
5    A0044  Agent A0044              430
6    A0020  Agent A0020              426
7    A0012  Agent A0012              425
8    A0015  Agent A0015              425
9    A0048  Agent A0048              425
10   A0016  Agent A0016              424
11   A0018  Agent A0018              422
12   A0031  Agent A0031              422
13   A0036  Agent A0036              422
14   A0033  Agent A0033              418
15   A0022  Agent A0022              417
16   A0040  Agent A0040              416
17   A0010  Agent A0010              415
18   A0027  Agent A0027              415
19   A0002  Agent A0002              414
20   A0037  Agent A0037              413
21   A0005  Agent A0005              412
22   A0026  Agent A0026              412
23   A0007  Agent A0007              411
24   A0035  Agent A0035              410
25   A0045  Agent A0045              410
26   A0009  Agent A0009              409
27   A0021  Agent A0021              409
28   A0050  Agent A0050              409
29   A0043  Agent A0043              408
30   A0028  Agent A0028              407
31   A0004  Agent A0004              406
32   A0032  Agent A0032              404
33   A0047  Agent A0047              404
34   A0006  Agent A0006              403
35   A0038  Agent A0038              401
36   A0041  Agent A0041              399
37   A0046  Agent A0046              397
38   A0030  Agent A0030              396
39   A0013  Agent A0013              395
40   A0029  Agent A0029              395
41   A0001  Agent A0001              392
42   A0017  Agent A0017              388
43   A0034  Agent A0034              388
44   A0049  Agent A0049              387
45   A0019  Agent A0019              386
46   A0025  Agent A0025              384
47   A0024  Agent A0024              380
48   A0039  Agent A0039              380
49   A0003  Agent A0003              379

Agents with the highest number of active listings are currently managing the largest property inventory.
A higher number of active listings may indicate greater market responsibility or a larger client portfolio, although it could also suggest that some properties are taking longer to sell.